//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IToUpper")]
public interface IToUpper
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToUpper/ToUpper", ReplyAction="http://tempuri.org/IToUpper/ToUpperResponse")]
    string ToUpper(string Input);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IToUpperChannel : IToUpper, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ToUpperClient : System.ServiceModel.ClientBase<IToUpper>, IToUpper
{
    
    public ToUpperClient()
    {
    }
    
    public ToUpperClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ToUpperClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ToUpperClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ToUpperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string ToUpper(string Input)
    {
        return base.Channel.ToUpper(Input);
    }
}
